/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface FirstWebComponent {}
}

declare global {


  interface HTMLFirstWebComponentElement extends Components.FirstWebComponent, HTMLStencilElement {}
  var HTMLFirstWebComponentElement: {
    prototype: HTMLFirstWebComponentElement;
    new (): HTMLFirstWebComponentElement;
  };
  interface HTMLElementTagNameMap {
    'first-web-component': HTMLFirstWebComponentElement;
  }
}

declare namespace LocalJSX {
  interface FirstWebComponent extends JSXBase.HTMLAttributes<HTMLFirstWebComponentElement> {}

  interface IntrinsicElements {
    'first-web-component': FirstWebComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


